import Head from 'next/head';
import { Inter } from 'next/font/google';
import DiseñoArq from '../components/DiseñoArq';
const inter = Inter({ subsets: ['latin'] });

export default function Services() {
  return (
    <>
      <Head>
        <title>Diseño</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DiseñoArq />
    </>
  );
}
